### ISSUE TITLE
module.exports is a function?

### ISSUE THREAD

**Issue by ljharb** [SimenB/util.promisify-all#2]
```js
function foo(callback) {}
foo.bar = function bar(callback) {};
module.exports = foo;
```

How does promisify-all work with this module?

**Comment by SimenB** [comment]
It promisifes `foo`, but `foo.bar` is the original function. Let's see what we can do about that 😄

**Comment by ljharb** [comment]
The goal imo should be that i get a new function, that's `!== foo`, but calls into `foo`. and then the new function's properties are all promisified versions of foo's properties.

**Comment by SimenB** [comment]
I _think_ that's what #3 accomplishes, unless my test is off?

**Comment by SimenB** [comment]
Wait, do you think that if a function is passed, thta function should not be promisified, only its properties?

**Comment by ljharb** [comment]
I'd expect it to be both promisified and proxied.
